# Generated by Django 5.1 on 2025-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=250)),
                ('desc', models.TextField()),
                ('image_id', models.CharField(max_length=300)),
                ('youtube_id', models.CharField(max_length=300)),
                ('github_link', models.CharField(max_length=300)),
                ('live_link', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=250)),
                ('field', models.CharField(max_length=300)),
                ('framework', models.CharField(max_length=250)),
                ('skills', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Project',
                'ordering': ['-created'],
            },
        ),
    ]
