# Generated by Django 5.1 on 2025-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_id',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
